[main]
terminal=kitty

font=JetBrainsMono Nerd Font:size=11
prompt=" :"
icon-theme=Papirus-Dark
lines=10
width=35
horizontal-pad=20
vertical-pad=15
inner-pad=5
#placeholder="Start typing..."

[colors]
background=1e1e2eff
text=adb6d4ee
match=f38ba8ff
selection=313244cc
selection-text=e6edf8ff
border=313244ff

[border]
width=2
radius=8

