font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12
disable_ligatures never
term xterm-kitty

allow_remote_control socket-only
listen_on unix:@mykitty

background #000000
background_opacity 0.75
dynamic_background_opacity yes

background_image none
background_image_layout cscaled
background_tint 0.9

mouse_hide_wait	-3.0
cursor_trail 500
cursor_trail_decay 0.05 0.2
cursor_trail_start_threshold 5

scrollback_lines 2000
