format = """$container $python$username$hostname: $directory$git_branch $git_status\n $character"""

[python]
style = "bold 126"
format = "[\\($virtualenv\\) ]($style)"
detect_extensions = []

[container]
style = "bold 130"
format = "[\\[$name\\]]($style)"

[username]
show_always = true
style_user = "bold 166"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bold 166"
format = "@[$hostname]($style)"

[directory]
style = "bold 170"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
style = "bold 139"
format = "([$symbol$branch]($style))"

[character]
success_symbol = "[❯](bold white) "
error_symbol = "[❯](bold red) "

